server:
  servlet:
    context-path: /sysin
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://172.19.33.161:3306/o2ophotography?useUnicode=true&characterEncoding=utf-8&useSSL=true&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: PncQNBodr2P7bdEE
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10

mybatis:
  mapper-locations: classpath:mapper/*.xml